### ISSUE TITLE
yolov4

### ISSUE THREAD

**Issue by lxy5513** [vlfom/CSD-detectron2#1]
I implemente csd with scaled-yolov4, but it's AP is decreased. have you plans to try it ?

**Comment by vlfom** [comment]
Hi, unfortunately, no, as Detectron2 [does not support YOLO](https://github.com/facebookresearch/detectron2/issues/215). But I'm not surprised that AP is decreased as that is what I also faced in my experiments. I suppose it's possible to get a _slight_ AP improvement by picking the right hyperparameters, though. You could try different training duration or learning rates.

Have you tried newer methods like [Unbiased Teacher](https://github.com/facebookresearch/unbiased-teacher/)? Motivated by FixMatch, I believe, it is way better, and they report outperforming CSD nearly 10x on some setups.

**Comment by lxy5513** [comment]
My colleague is researching `unbiased-teacher`,  I will try it soon.  
CSD is more simple, but as far as I consider, for semi-supervised, `self-training` method maybe more valid.

**Comment by vlfom** [comment]
I ran more experiments on VOC and just added a table with the results. CSD did not help me in any of the cases.

**Comment by vlfom** [comment]
Just wanted to let you know that I found a bug in my code, and after fixing it the CSD method started to bring improvements of about 1% in many scenarios on VOC. So now I'm more positive about the method's applicability. Sorry for the confusion before.

![image](https://user-images.githubusercontent.com/5049284/118635415-397b4480-b7dc-11eb-9a54-48627102f32d.png)
